name: screenshots

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: sudo apt update
    - run: sudo apt install -y python3-pytest python3-pip python3-selenium jq chromium-driver
    - run: mkdir test/artifacts
    - run: cd test ; python3 test.py
    - uses: actions/upload-artifact@v3
      with:
        name: screenshots
        path: test/artifacts/
